### PR TITLE
Changed all instances of theme.spacing.unit to theme.spacing().

### PR DESCRIPTION
**Pull request by thaigillespie**

### CODE REVIEW

**Comment by godwinpang** [comment]
can you squash the two commits together through rebasing? if not it's fine just go ahead and merge it in

**Comment by godwinpang** [comment]
feel free to make an issue and link it to close it too lmao

**Comment by thaigillespie** [comment]
I squashed the commits with git rebase. Can you review it or should I just merge and close the PR @godwinpang ?

**Comment by godwinpang** [comment]
lgtm go ahead and merge

**Pull request merged**
