### PR TITLE
Adds our own button component.

### PR DESCRIPTION
**Pull request by godwinpang**
This mirrors whatever is on figma

### CODE REVIEW

**Comment by godwinpang** [comment]
yeah I can see why this might be concerning from a dev perspective because we're circumventing the mui conventions. I designed this from a design standpoint; there should be one single primary button that pops out more on a page, and the rest can be secondary buttons so they dont distract from the primary action.

As for color, actions are either positive or negative so 🤷‍♂️ 
For positive/negative as props yeah we should probably can substitute it with a single field but I was too lazy to come up with a name for it; any thoughts?

**Comment by godwinpang** [comment]
check figma to see the buttons and see if it makes sense; i literally threw this together in like 5 minutes so I have 0 problems throwing this out

**Comment by thaigillespie** [comment]
I still don't really get what "positive" and "negative" really means. Like "positive" = button is being clicked on and "negative" = button not clicked on? 

Also, maybe we should use some other prop names for the variant field, just to avoid potential confusion? I'm not sure what those names should be tho, and this is just a small thing.

**Comment by godwinpang** [comment]
positive = submit, confirm
negative = cancel, delete

**Comment by godwinpang** [comment]
essentially instead of exposing the entire mui library we only let the developer choose between 2 things: connotation and emphasis level

**Comment by thaigillespie** [comment]
I see. Looks good to me then.

**Comment by godwinpang** [comment]
I'll add some documentation surrounding this stuff before merging in since it looks like the prop names aren't exactly transparent

**Comment by godwinpang** [comment]
this is what happens when you don't work on something for a while and don't keep your branches clean :)))) I guess my code's gone

**Comment by godwinpang** [comment]
and carelessly force push -_-

**Pull request closed without merging**
